version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "luis-p-test-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iq67aiu1indy"
s3_prefix = "luis-p-test-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EmailAddress=\"lopez470@umn.edu\""

